### ISSUE TITLE
Add support for Jetbrains compose desktop

### ISSUE THREAD

**Issue by sureshg** [mallumoSK/navigation#1]
This project is interesting, and I like the idea of code gen using KSP. Would be great if you can make it multiplatform and thus support compose desktop.

**Comment by mallumoSK** [comment]
Hi, it si in plan. 
**BUT** I waiting for more stable release of compose desktop **OR** any useful release for iOS. 
Then i made it full multiplatform. 
:)

**Comment by mallumoSK** [comment]
desktop -> done
js -> works but currently no examples ... will be, because hard to setup ...
